// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjMXB1G-4g9cIMna5xltXqnAPIIKk3jvw',
    appId: '1:1075425091036:web:eeb8b9d777137bbc9a8319',
    messagingSenderId: '1075425091036',
    projectId: 'aljoud-hospital',
    authDomain: 'aljoud-hospital.firebaseapp.com',
    storageBucket: 'aljoud-hospital.firebasestorage.app',
    measurementId: 'G-YWKWMDD6GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcrXb8qSTbjHkGmMsf0yynAW40XWCg0o',
    appId: '1:1075425091036:android:3b31ab5a2e0eb4629a8319',
    messagingSenderId: '1075425091036',
    projectId: 'aljoud-hospital',
    storageBucket: 'aljoud-hospital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEadFr80ZuowsYml0PqH0-50c40MF3oI',
    appId: '1:1075425091036:ios:848c0cf0f33e1f979a8319',
    messagingSenderId: '1075425091036',
    projectId: 'aljoud-hospital',
    storageBucket: 'aljoud-hospital.firebasestorage.app',
    iosBundleId: 'com.example.aljoudHospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjMXB1G-4g9cIMna5xltXqnAPIIKk3jvw',
    appId: '1:1075425091036:web:7b2f7a71f4f06c3c9a8319',
    messagingSenderId: '1075425091036',
    projectId: 'aljoud-hospital',
    authDomain: 'aljoud-hospital.firebaseapp.com',
    storageBucket: 'aljoud-hospital.firebasestorage.app',
    measurementId: 'G-781MEJX3XM',
  );

}